### ISSUE TITLE
Question about calculate the region of interest height and width

### ISSUE THREAD

**Issue by lilhope** [felixgwu/mask_rcnn_pytorch#2]
It maybe a naive question about I'm quite confused,when calculate the region of interest height and width,this code was use:
```
float roi_width = fmaxf(roi_end_w - roi_start_w + 1., 0.);
```
Why plus 1 after `roi_end_w - roi_start_w`?Is it force the width or height less than 1 to be 1?

**Comment by felixgwu** [comment]
Hi @lilhope,

Thanks for pointing it out.
There is a bug. It should be
```c
float roi_width = fmaxf(roi_end_w - roi_start_w + 1., 1.);
```
Here we treat pixels are discrete points, so the ROI includes the roi_start_w-th column and roi_end_w-th column. For instance, given that roi_end_w=4 and roi_start_w=2, the ROI should cover column 2, 3, and 4, so the width is 3.

**Comment by lilhope** [comment]
@felixgwu , correct me if I was wrong.Guess we have a rois `[0,1,2,15,14]`,and in the image ,its width is 15 ,height is 13.If we set the spitial_scale to 1/16,and in the feature map, its height should be 15/16 and 13/16.But if follow your code ,it  would be 30/16 and 28/16, seems it can't map back to the original image.

**Comment by felixgwu** [comment]
Yes, you are right. I should add 1 in the pixel space rather than in the feature space. Thank you for pointing it out.

**Comment by lilhope** [comment]
@felixgwu I still have a question,It seems we have two ways to calculate the aligned feature. Guess the aligned_height and aligned_width is 7,7, the first way is let `ph` and `pw` range from 0 to 6,and it outputs a feature map which shape is `[128,1024,7,7]`,then we do max/avg pooling with pad`(1,1)`. The second way is let `ph` and `pw` range from 0 to 7, and the output shape is `[128,1024,8,8]`, and we do pooling without pad.I don't know which one is right.Seems the second one will cover the whole rois.

**Comment by felixgwu** [comment]
@lilhope Sorry for the later response.
I think it's quite vaguely explained in the paper. Based on my understanding, it should be the second way.
However, I would wait for their official code to be released and continue the project.

**Comment by lilhope** [comment]
@felixgwu ok, same waiting for the official code. Thanks
