### ISSUE TITLE
Question 

### ISSUE THREAD

**Issue by blitu12345** [felixgwu/mask_rcnn_pytorch#3]
Is this source code capable enough to be used in production?Thank you 
@felixgwu .

**Comment by felixgwu** [comment]
Hi @blitu12345,
Unfortunately, it is not working yet. I faced out of memory error, so I could not debug yet. My assumption is that the authors of the paper used m40 GPUs with up to 24GB memory. However, I don't have a GPU with that much GPU. As there are some implementation details not explained clearly enough in the paper, so I am waiting for the authors to release the official implementation before continuing this project.

**Comment by blitu12345** [comment]
Okay got it! and thank you for a fast reply.

**Comment by jtoy** [comment]
is it useful to reference this one? https://github.com/CharlesShang/FastMaskRCNN

**Comment by blitu12345** [comment]
@jtoy that one still needs many improvements though.But thanks for pointing out !!
